services:
  db:
    image: postgres:15.4
    secrets:
      - db_password
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8001:8001"


  wordpress:
    depends_on:
      - db
    image: wordpress:6.3
    ports:
      - "8000:8000"
    environment:
      WORDPRESS_DB_HOST: db:5432
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

secrets:
  db_password:
    file: db_password.txt