version: '2'
services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: my-postgres # Replace 'mydatabase' with your desired database name
      POSTGRES_USER: myuser    # Replace 'myuser' with your desired database username
    ports:
      - "5432:5432"
    secrets:
      - db_password

  client:
    build: 
      context: ./client/python
      dockerfile: Dockerfile
    ports:
      - "8270:8270"

  wordpress:
    depends_on:
      - db
    image: wordpress:6.3
    ports:
      - "8000:8000"
    environment:
      WORDPRESS_DB_HOST: db:5432
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_NAME: mydatabase  # Replace 'mydatabase' with the same database name as defined for the db service
    secrets:
      - db_password

secrets:
  db_password:
    file: db_password.txt  # Replace with the path to your password file
